services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: teeworlds
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
